---
title: "beer"
author: "Andrew Norman"
date: "22 January 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(extrafont)
library(plyr)
library(RColorBrewer)
library(data.table)
library(raster)
library(grid)
library(maps)
source("beermap.r")

jBrewColSet <- brewer.pal(n = 11, name = "Spectral")
col1 <- brewer.pal(n=9, name="Blues")
col2 <- brewer.pal(n=9, name="Blues")
beers <- read.csv("checkin-report_01_08_17.csv", header=FALSE, col.names = c("name", "brewery", "type", "abv", "ibu", "comment", "venuename", "venuecity", "venuestate", "venuecountry", "lat", "long", "score", "created", "url1", "url2", "url3", "brewerycountry", "brewerycity", "brewerystate"), stringsAsFactors = FALSE)
beers$datetime <- as.POSIXct(beers$created, "%y-%m-%d %H:%M:%S")
beers$hour <- lubridate::hour(beers$datetime)
beers$summary.type <- map.beer.types(beers)
# Remove all non unique beers using the untappd beer url
unique.beers <- ddply(beers, .(url2), head, n = 1)
csum.types <- map.beer.cumulative.sum(beers)
```
International Bitterness Units versus Rating
```{r ibu}
#IBUs Vs Rating
plot(beers[beers$ibu > 0, ]$ibu, beers[beers$ibu > 0, ]$score, col=col1[6], main="IBUs Vs Rating", xlab="IBUs", ylab="Rating")
abline(lm(beers[beers$ibu > 0, ]$score~beers[beers$ibu > 0, ]$ibu), col=col2[4])
```
Summary
```{r summary ibu}
summary.lm(lm(beers[beers$ibu > 0, ]$score~beers[beers$ibu > 0, ]$ibu))
```
Alcohol By Volume versus Rating
```{r abv}
# ABV Vs Rating
plot(beers[beers$abv > 0, ]$abv, beers[beers$abv > 0, ]$score, col=col1[6], main="ABVs Vs Rating", xlab="ABVs", ylab="Rating")
abline(lm(beers[beers$abv > 0, ]$score~beers[beers$abv > 0, ]$ibu), col=col2[4])
summary.lm(lm(beers[beers$abv > 0, ]$score~beers[beers$abv > 0, ]$ibu))
```
Average rating of beers
```{r mean}
#average ratings of different types of beer
complist <- unique.beers[complete.cases(unique.beers$score),]
agglist <- aggregate(complist$score, by=list(complist$type), FUN=mean)
types.order <- order(as.numeric(agglist$x),decreasing = TRUE)
types <- agglist[types.order,]$x
names(types) <- agglist[types.order,]$Group.1
barplot(types, horiz=TRUE, col=col1, main="Average Rating by Type", xlab="Mean Rating")
```
Those beers with their types summarised
```{r summary mean}
complist <- unique.beers[complete.cases(unique.beers$score),]
summary.agglist <- aggregate(complist$score, by=list(complist$summary.type), FUN=mean)
types.order <- order(as.numeric(summary.agglist$x),decreasing = TRUE)
types <- summary.agglist[types.order,]$x
names(types) <- summary.agglist[types.order,]$Group.1
par(mai=c(1,2,1,1))
barplot(types, horiz=TRUE,las=1, col=c(col1[6], col2[4]), main="Average Rating by Subtype", xlab="Mean Rating")
```
IPA Subtypes
```{r ipa subtypes}
complist <- unique.beers[unique.beers$summary.type == 'IPA',]
summary.agglist <- aggregate(complist$score, by=list(complist$type), FUN=mean)
types.order <- order(as.numeric(summary.agglist$x),decreasing = TRUE)
types <- summary.agglist[types.order,]$x
names(types) <- summary.agglist[types.order,]$Group.1
par(mai=c(1,3,1,0))
barplot(types, horiz=TRUE,las=1, col=c(col1[6], col2[4]), main="Average Rating of IPA Types", xlab="Mean Rating")
```
Histograms of Checkins
```{r histogram}
# histogram of checkins
hist(unique.beers$score, breaks = seq(-0.25,5.25,by=0.5), col=c(col1[6], col2[4]), main="Histogram of Ratings, Rounded to Nearest 0.5", xlab="Rating")
```

```{r histogrampostquarter}
# histogram after quarter points
hist(unique.beers[unique.beers$datetime > as.POSIXct("2015-07-09"), ]$score, breaks = seq(0.125,5.125,by=0.25), col=c(col1[6], col2[4]), main="Histogram of Ratings Post August 2015, Unrounded", xlab="Rating")
```
Moving Averages
```{r moving average}
ma <- function(x,n=5){filter(x,rep(1/n,n), sides=2)}
# moving average rating
plot(ma(beers[complete.cases(beers$score),]$score, 10), col=col1[7], main="Moving Average of Ratings, N=5", xlab="Checkin Count", ylab="Mean Rating") 
# checking in time / rate of checking.
```
Time of the day
```{r time}
# time of day
hist(beers$hour, breaks = 24, col=c(col1[6], col2[4]), main="Beers Drunk Based on Checkin Time", xlab="Hour")
```
```{r time rating}
agglist_hour <- aggregate(beers[complete.cases(beers$score),]$score, by=list(beers[complete.cases(beers$score),]$hour), FUN=mean)
# Fill in empty values
for (hour in 0:23) {
  if (!(hour %in% agglist_hour$Group.1)) {
    agglist_hour <- rbind(agglist_hour, c(hour, 0))
  }
}
barplot(height=agglist_hour[order(agglist_hour$Group.1),]$x, names.arg=agglist_hour[order(agglist_hour$Group.1),]$Group.1, xlab="Hour of the Day", ylab="Average Rating", col=c(col1[6], col2[4]), font=2)
# hist(beers$time, breaks = seq(as.POSIXct("00:00:00", format="%H:%M:%S"), as.POSIXct("24:00:00", format="%H:%M:%S"),by="hour"))
```
```{r cumulative sum}
ggplot(csum.types, aes(x=time,y=val,group=var,fill=var)) + geom_area(position="fill")
```
World Plot of Checkins
```{r world map of checkins}
library(dplyr)
world <- map_data('world') %>% data.table()
world <- world[region!='Antartica',]
ckplot <- ggplot(world, aes(long, lat)) +
  geom_polygon(aes(group=group),fill="white",colour="black",size=0.1) +
  coord_equal() +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  labs(x='Longitude', y='Latitude') +
  theme_bw()
ckplot <- ckplot + geom_point(data=beers[complete.cases(beers$lat),], aes(long, lat))
ckplot
# Remove dplyr, it messes with 'fitler_' method
detach("package:dplyr", unload=TRUE)
```

World Plot of Brewery Countries
```{r world map of brewery countries}
library(rworldmap)
# joinCountryData2Map only has "United Kingdom"
unique.beers$brewerycountry[unique.beers$brewerycountry == "England"] <- "United Kingdom"
unique.beers$brewerycountry[unique.beers$brewerycountry == "Scotland"] <- "United Kingdom"
unique.beers$brewerycountry[unique.beers$brewerycountry == "Wales"] <- "United Kingdom"
unique.beers$brewerycountry[unique.beers$brewerycountry == "China / People's Republic of China"] <- "China"
countrytable <- table(unique.beers$brewerycountry)
cdf = data.frame(country=names(countrytable), count=as.vector(countrytable))
spdf <- joinCountryData2Map(cdf, joinCode="NAME", nameJoinColumn="country")
mapCountryData(spdf, nameColumnToPlot="count", catMethod="fixedWidth")
```